// Pre-operational checklist — Local Partner Mexico (Expedición Roblox México)
// Source content in Portuguese. Each task gets a stable id `s{section}t{index}`
// used for persistence — do not reorder existing entries.

export const CHECKLIST = [
  {
    n: 1,
    title: 'Governança e alinhamento inicial',
    tasks: [
      { task: 'Confirmar ponto focal único do parceiro local para interface com Mastertech e Roblox', deliverable: 'Nome, e-mail, WhatsApp e papel definido', resp: 'Aurora' },
      { task: 'Criar grupo operacional com Mastertech, Aurora e Roblox, se aplicável', deliverable: 'Canal oficial de comunicação ativo', resp: 'Aurora + Mastertech' },
      { task: 'Validar calendário macro das 5 ativações locais', deliverable: 'Cronograma preliminar por cidade/local', resp: 'Aurora' },
      { task: 'Confirmar quais 2 eventos terão presença de facilitador Mastertech', deliverable: 'Lista de eventos prioritários para visita presencial', resp: 'Aurora + Mastertech' },
      { task: 'Definir cadência de reuniões operacionais', deliverable: 'Reuniões semanais ou quinzenais agendadas', resp: 'Aurora + Mastertech' },
      { task: 'Revisar o escopo do parceiro local e limites de responsabilidade da Mastertech', deliverable: 'Matriz RACI validada', resp: 'Aurora + Mastertech' },
    ],
  },
  {
    n: 2,
    title: 'Mapeamento institucional e articulação pública',
    tasks: [
      { task: 'Mapear stakeholders federais, estaduais e locais relevantes', deliverable: 'Lista de contatos institucionais priorizada', resp: 'Aurora' },
      { task: 'Identificar pontos de entrada com SEP, SEDECO, PILARES, UTOPÍAS e comissões locais de educação', deliverable: 'Plano de aproximação institucional', resp: 'Aurora' },
      { task: 'Preparar narrativa institucional da Expedición Roblox México para reuniões locais', deliverable: 'Pitch institucional adaptado ao México', resp: 'Aurora + Mastertech' },
      { task: 'Agendar primeiras reuniões com instituições parceiras', deliverable: 'Calendário de reuniões confirmado', resp: 'Aurora' },
      { task: 'Levantar requisitos formais para uso de espaços públicos ou educacionais', deliverable: 'Lista de permissões, documentos e prazos', resp: 'Aurora' },
      { task: 'Confirmar se haverá presença de representantes públicos nos eventos', deliverable: 'Lista de convidados institucionais', resp: 'Aurora' },
    ],
  },
  {
    n: 3,
    title: 'Seleção e validação de locais',
    tasks: [
      { task: 'Definir as cidades e regiões das 5 ativações locais', deliverable: 'Lista final de localidades', resp: 'Aurora' },
      { task: 'Selecionar venues adequados para oficinas presenciais', deliverable: 'Lista de espaços com capacidade, endereço e responsável', resp: 'Aurora' },
      { task: 'Verificar capacidade mínima por local', deliverable: 'Confirmação de pelo menos 50 estudantes na Cidade do México e 25 em venues regionais, conforme o SOW', resp: 'Aurora' },
      { task: 'Auditar infraestrutura técnica dos espaços', deliverable: 'Checklist de internet, energia, computadores, projetor e som', resp: 'Aurora' },
      { task: 'Confirmar acessibilidade e segurança dos espaços', deliverable: 'Validação de acesso, banheiros, entrada/saída e controle de público', resp: 'Aurora' },
      { task: 'Reservar formalmente os venues', deliverable: 'Confirmações por escrito', resp: 'Aurora' },
      { task: 'Definir layout da sala para estudantes, famílias, educadores e equipe técnica', deliverable: 'Planta ou orientação operacional', resp: 'Aurora' },
    ],
  },
  {
    n: 4,
    title: 'Mobilização de participantes',
    tasks: [
      { task: 'Definir público-alvo por ativação', deliverable: 'Segmentação de jovens de 13 a 18 anos, famílias e educadores', resp: 'Aurora' },
      { task: 'Criar plano de recrutamento por cidade/local', deliverable: 'Meta de inscritos e comparecimento por evento', resp: 'Aurora' },
      { task: 'Ativar escolas secundárias, instituições técnicas e redes comunitárias', deliverable: 'Lista de parceiros mobilizadores', resp: 'Aurora' },
      { task: 'Estabelecer pipeline de inscrições', deliverable: 'Formulário, landing page ou processo de cadastro validado', resp: 'Aurora + Mastertech' },
      { task: 'Criar mensagens de convite para estudantes', deliverable: 'Texto em espanhol mexicano aprovado', resp: 'Aurora + Roblox/Mastertech' },
      { task: 'Criar mensagens de convite para pais e responsáveis', deliverable: 'Texto de confiança e segurança aprovado', resp: 'Aurora + Roblox/Mastertech' },
      { task: 'Criar mensagens para educadores e instituições', deliverable: 'Kit de convite institucional', resp: 'Aurora' },
      { task: 'Monitorar inscrições semanalmente', deliverable: 'Relatório de funil: convidados, inscritos, confirmados', resp: 'Aurora' },
      { task: 'Criar plano de overbooking saudável', deliverable: 'Estratégia para garantir presença mínima', resp: 'Aurora' },
      { task: 'Enviar lembretes antes dos eventos', deliverable: 'Sequência de confirmação por e-mail/WhatsApp', resp: 'Aurora' },
    ],
  },
  {
    n: 5,
    title: 'Comunicação local e materiais públicos',
    tasks: [
      { task: 'Levantar necessidades de comunicação local', deliverable: 'Lista de peças necessárias por canal', resp: 'Aurora' },
      { task: 'Adaptar textos para espanhol mexicano, mantendo diretrizes Roblox', deliverable: 'Cópias locais revisadas', resp: 'Aurora + Mastertech' },
      { task: 'Submeter peças públicas à aprovação da Roblox', deliverable: 'Registro de aprovações', resp: 'Aurora + Roblox' },
      { task: 'Preparar kit de comunicação para escolas e instituições', deliverable: 'E-mail, folder, apresentação curta e FAQ', resp: 'Aurora' },
      { task: 'Preparar FAQ para famílias', deliverable: 'Documento com segurança, aprendizagem, Roblox Studio e objetivos do programa', resp: 'Aurora + Mastertech' },
      { task: 'Criar plano de divulgação por parceiro institucional', deliverable: 'Cronograma de disparos e responsáveis', resp: 'Aurora' },
      { task: 'Validar uso correto de marca Roblox e Expedición Roblox México', deliverable: 'Checklist de brand compliance', resp: 'Roblox + Aurora' },
    ],
  },
  {
    n: 6,
    title: 'Recrutamento e preparação de equipe local',
    tasks: [
      { task: 'Definir quantidade de treinadores por evento', deliverable: 'Escala de facilitadores e assistentes técnicos', resp: 'Aurora' },
      { task: 'Recrutar treinadores locais com perfil técnico-pedagógico', deliverable: 'Lista de selecionados', resp: 'Aurora' },
      { task: 'Recrutar assistentes técnicos para suporte em Roblox Studio', deliverable: 'Lista de apoio técnico', resp: 'Aurora' },
      { task: 'Validar disponibilidade da equipe em todas as datas', deliverable: 'Escala final', resp: 'Aurora' },
      { task: 'Organizar treinamento com base nas diretrizes Mastertech', deliverable: 'Sessão de onboarding realizada', resp: 'Aurora + Mastertech' },
      { task: 'Garantir que treinadores dominem os checkpoints: ideação, prototipação, construção e publicação', deliverable: 'Checklist de proficiência por treinador', resp: 'Aurora' },
      { task: 'Criar roteiro operacional para facilitadores locais', deliverable: 'Guia do dia do evento', resp: 'Aurora + Mastertech' },
      { task: 'Definir protocolo de suporte técnico durante as oficinas', deliverable: 'Fluxo de resolução de problemas', resp: 'Aurora' },
    ],
  },
  {
    n: 7,
    title: 'Preparação técnica',
    tasks: [
      { task: 'Confirmar disponibilidade de computadores ou notebooks', deliverable: 'Inventário por venue', resp: 'Aurora' },
      { task: 'Confirmar instalação e funcionamento do Roblox Studio', deliverable: 'Checklist técnico por máquina', resp: 'Aurora' },
      { task: 'Testar acesso ao Learning Environment/plugin distribuído pela Mastertech', deliverable: 'Evidência de teste bem-sucedido', resp: 'Aurora + Mastertech' },
      { task: 'Testar internet com carga simulada', deliverable: 'Resultado de teste de velocidade e estabilidade', resp: 'Aurora' },
      { task: 'Preparar plano B para falhas de conexão', deliverable: 'Hotspots, rede alternativa ou conteúdo offline de apoio', resp: 'Aurora' },
      { task: 'Validar contas ou fluxo de acesso dos participantes', deliverable: 'Processo de login/cadastro testado', resp: 'Aurora' },
      { task: 'Verificar restrições de rede em escolas ou espaços públicos', deliverable: 'Liberação de domínios e permissões técnicas', resp: 'Aurora' },
      { task: 'Preparar equipamentos de projeção e áudio', deliverable: 'Checklist audiovisual', resp: 'Aurora' },
      { task: 'Criar kit técnico por evento', deliverable: 'Cabos, extensões, adaptadores, réguas, carregadores', resp: 'Aurora' },
    ],
  },
  {
    n: 8,
    title: 'Jornada do evento presencial',
    tasks: [
      { task: 'Adaptar blueprint da jornada desenhada pela Mastertech para cada local', deliverable: 'Agenda local por evento', resp: 'Aurora + Mastertech' },
      { task: 'Definir horário de chegada da equipe', deliverable: 'Call time operacional', resp: 'Aurora' },
      { task: 'Definir fluxo de recepção e check-in', deliverable: 'Processo de credenciamento', resp: 'Aurora' },
      { task: 'Preparar abertura institucional', deliverable: 'Roteiro de boas-vindas', resp: 'Aurora' },
      { task: 'Organizar dinâmica para estudantes', deliverable: 'Roteiro de oficina alinhado à metodologia', resp: 'Aurora + Mastertech' },
      { task: 'Organizar sessão de engajamento familiar', deliverable: 'Roteiro para pais/responsáveis', resp: 'Aurora' },
      { task: 'Definir momentos de coleta de dados durante o evento', deliverable: 'Checkpoints de registro', resp: 'Aurora' },
      { task: 'Definir encerramento e próximos passos', deliverable: 'Roteiro de fechamento e convite para continuidade/Game Jam', resp: 'Aurora' },
      { task: 'Criar plano de contingência para atrasos, baixa presença ou falhas técnicas', deliverable: 'Matriz de riscos por evento', resp: 'Aurora' },
    ],
  },
  {
    n: 9,
    title: 'Dados, métricas e comprovação de impacto',
    tasks: [
      { task: 'Validar com Mastertech quais dados devem ser coletados', deliverable: 'Dicionário de dados aprovado', resp: 'Aurora + Mastertech' },
      { task: 'Preparar formulário de inscrição com dados demográficos necessários', deliverable: 'Formulário validado', resp: 'Aurora' },
      { task: 'Preparar controle de presença', deliverable: 'Lista de check-in por evento', resp: 'Aurora' },
      { task: 'Criar mecanismo para verificar "net new creators"', deliverable: 'Fluxo de comprovação de publicação no Roblox Studio', resp: 'Aurora + Mastertech' },
      { task: 'Coletar dados de estudantes, educadores, pais e responsáveis', deliverable: 'Base bruta padronizada', resp: 'Aurora' },
      { task: 'Aplicar pesquisa de NPS/satisfação', deliverable: 'Formulário de avaliação', resp: 'Aurora' },
      { task: 'Garantir fluxo contínuo de informações para Mastertech', deliverable: 'Envio periódico de base e indicadores', resp: 'Aurora' },
      { task: 'Preparar documentação de campo de cada evento', deliverable: 'Fotos autorizadas, lista de presença, ocorrências e aprendizados', resp: 'Aurora' },
      { task: 'Consolidar dados das 5 ativações locais', deliverable: 'Base única para relatório global', resp: 'Aurora + Mastertech' },
    ],
  },
  {
    n: 10,
    title: 'Privacidade, consentimento e proteção de menores',
    tasks: [
      { task: 'Validar requisitos locais para participação de menores de idade', deliverable: 'Checklist jurídico-operacional', resp: 'Aurora' },
      { task: 'Criar ou adaptar termo de autorização de pais/responsáveis', deliverable: 'Termo em espanhol mexicano', resp: 'Aurora + Roblox/Mastertech' },
      { task: 'Definir política de uso de imagem', deliverable: 'Termo de imagem e consentimento', resp: 'Aurora' },
      { task: 'Garantir armazenamento seguro dos dados coletados', deliverable: 'Procedimento de proteção de dados', resp: 'Aurora' },
      { task: 'Separar dados operacionais de dados sensíveis', deliverable: 'Estrutura de base segura', resp: 'Aurora' },
      { task: 'Orientar equipe local sobre tratamento de dados de menores', deliverable: 'Briefing de privacidade', resp: 'Aurora' },
      { task: 'Confirmar alinhamento com DPA Roblox/Mastertech quando aplicável', deliverable: 'Registro de conformidade', resp: 'Aurora + Mastertech/Roblox' },
    ],
  },
  {
    n: 11,
    title: 'Game Jams e continuidade pós-evento',
    tasks: [
      { task: 'Entender regras, elegibilidade e rubricas definidas pela Mastertech', deliverable: 'Guia local de Game Jam', resp: 'Aurora + Mastertech' },
      { task: 'Preparar comunicação para convidar participantes aos desafios', deliverable: 'Convite pós-evento', resp: 'Aurora' },
      { task: 'Definir canal de suporte aos jovens participantes', deliverable: 'WhatsApp, Discord, e-mail ou outro canal aprovado', resp: 'Aurora' },
      { task: 'Organizar acompanhamento dos projetos iniciados nos eventos', deliverable: 'Lista de participantes e status dos projetos', resp: 'Aurora' },
      { task: 'Apoiar submissão de experiências criadas pelos estudantes', deliverable: 'Registro de submissões', resp: 'Aurora' },
      { task: 'Garantir que os projetos submetidos possam ser avaliados conforme rubrica', deliverable: 'Pacote de avaliação por participante/equipe', resp: 'Aurora' },
      { task: 'Enviar resultados e evidências à Mastertech', deliverable: 'Relatório de continuidade', resp: 'Aurora' },
    ],
  },
];

export const CHECKLIST_TOTAL = CHECKLIST.reduce((s, sec) => s + sec.tasks.length, 0);
