// Pre-operational checklist — Local Partner Mexico (Expedición Roblox México)
// Each translatable field is { pt, en, es }. `resp` marks involvement and keeps
// existing source naming only for deriving Mexico/Brazil badges in the UI.
// Task ids are `s{section}t{index}`
// (derived in the component) and are used for persistence — do not reorder.

export const CHECKLIST = [
  {
    n: 1,
    title: { pt: 'Governança e alinhamento inicial', en: 'Governance and initial alignment', es: 'Gobernanza y alineación inicial' },
    tasks: [
      { task: { pt: 'Confirmar ponto focal único do parceiro local para interface com Mastertech e Roblox', en: 'Confirm a single point of contact at the local partner to interface with Mastertech and Roblox', es: 'Confirmar un punto focal único del socio local para la interfaz con Mastertech y Roblox' }, deliverable: { pt: 'Nome, e-mail, WhatsApp e papel definido', en: 'Name, email, WhatsApp and role defined', es: 'Nombre, correo, WhatsApp y rol definido' }, resp: 'Aurora' },
      { task: { pt: 'Criar grupo operacional com Mastertech, Aurora e Roblox, se aplicável', en: 'Create an operational group with Mastertech, Aurora and Roblox, if applicable', es: 'Crear un grupo operativo con Mastertech, Aurora y Roblox, si aplica' }, deliverable: { pt: 'Canal oficial de comunicação ativo', en: 'Active official communication channel', es: 'Canal oficial de comunicación activo' }, resp: 'Aurora + Mastertech' },
      { task: { pt: 'Validar calendário macro das 5 ativações locais', en: 'Validate the macro calendar of the 5 local activations', es: 'Validar el calendario macro de las 5 activaciones locales' }, deliverable: { pt: 'Cronograma preliminar por cidade/local', en: 'Preliminary schedule by city/venue', es: 'Cronograma preliminar por ciudad/sede' }, resp: 'Aurora' },
      { task: { pt: 'Confirmar quais 2 eventos terão presença de facilitador Mastertech', en: 'Confirm which 2 events will have a Mastertech facilitator present', es: 'Confirmar cuáles 2 eventos tendrán presencia de facilitador Mastertech' }, deliverable: { pt: 'Lista de eventos prioritários para visita presencial', en: 'List of priority events for in-person visit', es: 'Lista de eventos prioritarios para visita presencial' }, resp: 'Aurora + Mastertech' },
    ],
  },
  {
    n: 2,
    title: { pt: 'Mapeamento institucional e articulação pública', en: 'Institutional mapping and public engagement', es: 'Mapeo institucional y articulación pública' },
    tasks: [
      { task: { pt: 'Mapear stakeholders federais, estaduais e locais relevantes', en: 'Map relevant federal, state and local stakeholders', es: 'Mapear stakeholders federales, estatales y locales relevantes' }, deliverable: { pt: 'Lista de contatos institucionais priorizada', en: 'Prioritized list of institutional contacts', es: 'Lista priorizada de contactos institucionales' }, resp: 'Aurora' },
      { task: { pt: 'Identificar pontos de entrada com SEP, SEDECO, PILARES, UTOPÍAS e comissões locais de educação', en: 'Identify entry points with SEP, SEDECO, PILARES, UTOPÍAS and local education commissions', es: 'Identificar puntos de entrada con SEP, SEDECO, PILARES, UTOPÍAS y comisiones locales de educación' }, deliverable: { pt: 'Plano de aproximação institucional', en: 'Institutional outreach plan', es: 'Plan de acercamiento institucional' }, resp: 'Aurora' },
      { task: { pt: 'Preparar narrativa institucional da Expedición Roblox México para reuniões locais', en: 'Prepare the institutional narrative of Expedición Roblox México for local meetings', es: 'Preparar la narrativa institucional de Expedición Roblox México para reuniones locales' }, deliverable: { pt: 'Pitch institucional adaptado ao México', en: 'Institutional pitch adapted to Mexico', es: 'Pitch institucional adaptado a México' }, resp: 'Aurora + Mastertech' },
      { task: { pt: 'Agendar primeiras reuniões com instituições parceiras', en: 'Schedule first meetings with partner institutions', es: 'Agendar primeras reuniones con instituciones socias' }, deliverable: { pt: 'Calendário de reuniões confirmado', en: 'Confirmed meeting calendar', es: 'Calendario de reuniones confirmado' }, resp: 'Aurora' },
      { task: { pt: 'Levantar requisitos formais para uso de espaços públicos ou educacionais', en: 'Gather formal requirements for using public or educational spaces', es: 'Levantar requisitos formales para el uso de espacios públicos o educativos' }, deliverable: { pt: 'Lista de permissões, documentos e prazos', en: 'List of permits, documents and deadlines', es: 'Lista de permisos, documentos y plazos' }, resp: 'Aurora' },
      { task: { pt: 'Confirmar se haverá presença de representantes públicos nos eventos', en: 'Confirm whether public representatives will attend the events', es: 'Confirmar si habrá presencia de representantes públicos en los eventos' }, deliverable: { pt: 'Lista de convidados institucionais', en: 'List of institutional guests', es: 'Lista de invitados institucionales' }, resp: 'Aurora' },
    ],
  },
  {
    n: 3,
    title: { pt: 'Seleção e validação de locais', en: 'Venue selection and validation', es: 'Selección y validación de sedes' },
    tasks: [
      { task: { pt: 'Definir as cidades e regiões das 5 ativações locais', en: 'Define the cities and regions of the 5 local activations', es: 'Definir las ciudades y regiones de las 5 activaciones locales' }, deliverable: { pt: 'Lista final de localidades', en: 'Final list of locations', es: 'Lista final de localidades' }, resp: 'Aurora' },
      { task: { pt: 'Selecionar venues adequados para oficinas presenciais', en: 'Select suitable venues for in-person workshops', es: 'Seleccionar sedes adecuadas para talleres presenciales' }, deliverable: { pt: 'Lista de espaços com capacidade, endereço e responsável', en: 'List of spaces with capacity, address and contact', es: 'Lista de espacios con capacidad, dirección y responsable' }, resp: 'Aurora' },
      { task: { pt: 'Verificar capacidade mínima por local', en: 'Verify minimum capacity per venue', es: 'Verificar capacidad mínima por sede' }, deliverable: { pt: 'Confirmação de pelo menos 50 estudantes na Cidade do México e 25 em venues regionais, conforme o SOW', en: 'Confirmation of at least 50 students in Mexico City and 25 at regional venues, per the SOW', es: 'Confirmación de al menos 50 estudiantes en Ciudad de México y 25 en sedes regionales, según el SOW' }, resp: 'Aurora' },
      { task: { pt: 'Auditar infraestrutura técnica dos espaços', en: 'Audit the technical infrastructure of the spaces', es: 'Auditar la infraestructura técnica de los espacios' }, deliverable: { pt: 'Checklist de internet, energia, computadores, projetor e som', en: 'Checklist of internet, power, computers, projector and sound', es: 'Checklist de internet, energía, computadoras, proyector y sonido' }, resp: 'Aurora' },
      { task: { pt: 'Confirmar acessibilidade e segurança dos espaços', en: 'Confirm accessibility and safety of the spaces', es: 'Confirmar accesibilidad y seguridad de los espacios' }, deliverable: { pt: 'Validação de acesso, banheiros, entrada/saída e controle de público', en: 'Validation of access, restrooms, entry/exit and crowd control', es: 'Validación de acceso, baños, entrada/salida y control de público' }, resp: 'Aurora' },
      { task: { pt: 'Reservar formalmente os venues', en: 'Formally book the venues', es: 'Reservar formalmente las sedes' }, deliverable: { pt: 'Confirmações por escrito', en: 'Written confirmations', es: 'Confirmaciones por escrito' }, resp: 'Aurora' },
      { task: { pt: 'Definir layout da sala para estudantes, famílias, educadores e equipe técnica', en: 'Define the room layout for students, families, educators and technical team', es: 'Definir el layout de la sala para estudiantes, familias, educadores y equipo técnico' }, deliverable: { pt: 'Planta ou orientação operacional', en: 'Floor plan or operational guidance', es: 'Plano o guía operativa' }, resp: 'Aurora' },
    ],
  },
  {
    n: 4,
    title: { pt: 'Mobilização de participantes', en: 'Participant mobilization', es: 'Movilización de participantes' },
    tasks: [
      { task: { pt: 'Definir público-alvo por ativação', en: 'Define the target audience per activation', es: 'Definir el público objetivo por activación' }, deliverable: { pt: 'Segmentação de jovens de 13 a 18 anos, famílias e educadores', en: 'Segmentation of youth aged 13–18, families and educators', es: 'Segmentación de jóvenes de 13 a 18 años, familias y educadores' }, resp: 'Aurora' },
      { task: { pt: 'Criar plano de recrutamento por cidade/local', en: 'Create a recruitment plan per city/venue', es: 'Crear un plan de reclutamiento por ciudad/sede' }, deliverable: { pt: 'Meta de inscritos e comparecimento por evento', en: 'Target of registrations and attendance per event', es: 'Meta de inscritos y asistencia por evento' }, resp: 'Aurora' },
      { task: { pt: 'Ativar escolas secundárias, instituições técnicas e redes comunitárias', en: 'Activate secondary schools, technical institutions and community networks', es: 'Activar escuelas secundarias, instituciones técnicas y redes comunitarias' }, deliverable: { pt: 'Lista de parceiros mobilizadores', en: 'List of mobilizing partners', es: 'Lista de socios movilizadores' }, resp: 'Aurora' },
      { task: { pt: 'Estabelecer pipeline de inscrições', en: 'Establish a registration pipeline', es: 'Establecer un pipeline de inscripciones' }, deliverable: { pt: 'Formulário, landing page ou processo de cadastro validado', en: 'Validated form, landing page or registration process', es: 'Formulario, landing page o proceso de registro validado' }, resp: 'Aurora + Mastertech' },
      { task: { pt: 'Criar mensagens de convite para estudantes', en: 'Create invitation messages for students', es: 'Crear mensajes de invitación para estudiantes' }, deliverable: { pt: 'Texto em espanhol mexicano aprovado', en: 'Approved Mexican Spanish copy', es: 'Texto en español mexicano aprobado' }, resp: 'Aurora + Roblox/Mastertech' },
      { task: { pt: 'Criar mensagens de convite para pais e responsáveis', en: 'Create invitation messages for parents and guardians', es: 'Crear mensajes de invitación para padres y tutores' }, deliverable: { pt: 'Texto de confiança e segurança aprovado', en: 'Approved trust and safety copy', es: 'Texto de confianza y seguridad aprobado' }, resp: 'Aurora + Roblox/Mastertech' },
      { task: { pt: 'Criar mensagens para educadores e instituições', en: 'Create messages for educators and institutions', es: 'Crear mensajes para educadores e instituciones' }, deliverable: { pt: 'Kit de convite institucional', en: 'Institutional invitation kit', es: 'Kit de invitación institucional' }, resp: 'Aurora' },
      { task: { pt: 'Monitorar inscrições semanalmente', en: 'Monitor registrations weekly', es: 'Monitorear inscripciones semanalmente' }, deliverable: { pt: 'Relatório de funil: convidados, inscritos, confirmados', en: 'Funnel report: invited, registered, confirmed', es: 'Reporte de embudo: invitados, inscritos, confirmados' }, resp: 'Aurora' },
      { task: { pt: 'Criar plano de overbooking saudável', en: 'Create a healthy overbooking plan', es: 'Crear un plan de overbooking saludable' }, deliverable: { pt: 'Estratégia para garantir presença mínima', en: 'Strategy to ensure minimum attendance', es: 'Estrategia para garantizar la asistencia mínima' }, resp: 'Aurora' },
      { task: { pt: 'Enviar lembretes antes dos eventos', en: 'Send reminders before the events', es: 'Enviar recordatorios antes de los eventos' }, deliverable: { pt: 'Sequência de confirmação por e-mail/WhatsApp', en: 'Confirmation sequence via email/WhatsApp', es: 'Secuencia de confirmación por correo/WhatsApp' }, resp: 'Aurora' },
    ],
  },
  {
    n: 5,
    title: { pt: 'Comunicação local e materiais públicos', en: 'Local communication and public materials', es: 'Comunicación local y materiales públicos' },
    tasks: [
      { task: { pt: 'Levantar necessidades de comunicação local', en: 'Identify local communication needs', es: 'Levantar necesidades de comunicación local' }, deliverable: { pt: 'Lista de peças necessárias por canal', en: 'List of needed assets per channel', es: 'Lista de piezas necesarias por canal' }, resp: 'Aurora' },
      { task: { pt: 'Adaptar textos para espanhol mexicano, mantendo diretrizes Roblox', en: 'Adapt copy to Mexican Spanish, keeping Roblox guidelines', es: 'Adaptar textos al español mexicano, manteniendo las directrices de Roblox' }, deliverable: { pt: 'Cópias locais revisadas', en: 'Reviewed local copies', es: 'Copias locales revisadas' }, resp: 'Aurora + Mastertech' },
      { task: { pt: 'Submeter peças públicas à aprovação da Roblox', en: 'Submit public assets for Roblox approval', es: 'Someter las piezas públicas a la aprobación de Roblox' }, deliverable: { pt: 'Registro de aprovações', en: 'Record of approvals', es: 'Registro de aprobaciones' }, resp: 'Aurora + Roblox' },
      { task: { pt: 'Preparar kit de comunicação para escolas e instituições', en: 'Prepare a communication kit for schools and institutions', es: 'Preparar un kit de comunicación para escuelas e instituciones' }, deliverable: { pt: 'E-mail, folder, apresentação curta e FAQ', en: 'Email, flyer, short presentation and FAQ', es: 'Correo, folleto, presentación corta y FAQ' }, resp: 'Aurora' },
      { task: { pt: 'Preparar FAQ para famílias', en: 'Prepare an FAQ for families', es: 'Preparar un FAQ para familias' }, deliverable: { pt: 'Documento com segurança, aprendizagem, Roblox Studio e objetivos do programa', en: 'Document covering safety, learning, Roblox Studio and program objectives', es: 'Documento con seguridad, aprendizaje, Roblox Studio y objetivos del programa' }, resp: 'Aurora + Mastertech' },
      { task: { pt: 'Criar plano de divulgação por parceiro institucional', en: 'Create a promotion plan per institutional partner', es: 'Crear un plan de difusión por socio institucional' }, deliverable: { pt: 'Cronograma de disparos e responsáveis', en: 'Schedule of sends and owners', es: 'Cronograma de envíos y responsables' }, resp: 'Aurora' },
      { task: { pt: 'Validar uso correto de marca Roblox e Expedición Roblox México', en: 'Validate correct use of the Roblox and Expedición Roblox México brand', es: 'Validar el uso correcto de la marca Roblox y Expedición Roblox México' }, deliverable: { pt: 'Checklist de brand compliance', en: 'Brand compliance checklist', es: 'Checklist de cumplimiento de marca' }, resp: 'Roblox + Aurora' },
    ],
  },
  {
    n: 6,
    title: { pt: 'Recrutamento e preparação de equipe local', en: 'Recruiting and preparing the local team', es: 'Reclutamiento y preparación del equipo local' },
    tasks: [
      { task: { pt: 'Definir quantidade de treinadores por evento', en: 'Define the number of trainers per event', es: 'Definir la cantidad de capacitadores por evento' }, deliverable: { pt: 'Escala de facilitadores e assistentes técnicos', en: 'Schedule of facilitators and technical assistants', es: 'Programación de facilitadores y asistentes técnicos' }, resp: 'Aurora' },
      { task: { pt: 'Recrutar treinadores locais com perfil técnico-pedagógico', en: 'Recruit local trainers with a technical-pedagogical profile', es: 'Reclutar capacitadores locales con perfil técnico-pedagógico' }, deliverable: { pt: 'Lista de selecionados', en: 'List of selected candidates', es: 'Lista de seleccionados' }, resp: 'Aurora' },
      { task: { pt: 'Recrutar assistentes técnicos para suporte em Roblox Studio', en: 'Recruit technical assistants for Roblox Studio support', es: 'Reclutar asistentes técnicos para soporte en Roblox Studio' }, deliverable: { pt: 'Lista de apoio técnico', en: 'Technical support list', es: 'Lista de apoyo técnico' }, resp: 'Aurora' },
      { task: { pt: 'Validar disponibilidade da equipe em todas as datas', en: 'Validate team availability on all dates', es: 'Validar la disponibilidad del equipo en todas las fechas' }, deliverable: { pt: 'Escala final', en: 'Final schedule', es: 'Programación final' }, resp: 'Aurora' },
      { task: { pt: 'Organizar treinamento com base nas diretrizes Mastertech', en: 'Organize training based on Mastertech guidelines', es: 'Organizar la capacitación con base en las directrices de Mastertech' }, deliverable: { pt: 'Sessão de onboarding realizada', en: 'Onboarding session completed', es: 'Sesión de onboarding realizada' }, resp: 'Aurora + Mastertech' },
      { task: { pt: 'Garantir que treinadores dominem os checkpoints: ideação, prototipação, construção e publicação', en: 'Ensure trainers master the checkpoints: ideation, prototyping, building and publishing', es: 'Asegurar que los capacitadores dominen los checkpoints: ideación, prototipado, construcción y publicación' }, deliverable: { pt: 'Checklist de proficiência por treinador', en: 'Proficiency checklist per trainer', es: 'Checklist de competencia por capacitador' }, resp: 'Aurora' },
      { task: { pt: 'Criar roteiro operacional para facilitadores locais', en: 'Create an operational script for local facilitators', es: 'Crear un guion operativo para facilitadores locales' }, deliverable: { pt: 'Guia do dia do evento', en: 'Event-day guide', es: 'Guía del día del evento' }, resp: 'Aurora + Mastertech' },
      { task: { pt: 'Definir protocolo de suporte técnico durante as oficinas', en: 'Define the technical support protocol during the workshops', es: 'Definir el protocolo de soporte técnico durante los talleres' }, deliverable: { pt: 'Fluxo de resolução de problemas', en: 'Troubleshooting flow', es: 'Flujo de resolución de problemas' }, resp: 'Aurora' },
    ],
  },
  {
    n: 7,
    title: { pt: 'Preparação técnica', en: 'Technical preparation', es: 'Preparación técnica' },
    tasks: [
      { task: { pt: 'Confirmar disponibilidade de computadores ou notebooks', en: 'Confirm availability of computers or laptops', es: 'Confirmar disponibilidad de computadoras o laptops' }, deliverable: { pt: 'Inventário por venue', en: 'Inventory per venue', es: 'Inventario por sede' }, resp: 'Aurora' },
      { task: { pt: 'Confirmar instalação e funcionamento do Roblox Studio', en: 'Confirm Roblox Studio installation and operation', es: 'Confirmar la instalación y el funcionamiento de Roblox Studio' }, deliverable: { pt: 'Checklist técnico por máquina', en: 'Technical checklist per machine', es: 'Checklist técnico por máquina' }, resp: 'Aurora' },
      { task: { pt: 'Testar acesso ao Learning Environment/plugin distribuído pela Mastertech', en: 'Test access to the Learning Environment/plugin distributed by Mastertech', es: 'Probar el acceso al Learning Environment/plugin distribuido por Mastertech' }, deliverable: { pt: 'Evidência de teste bem-sucedido', en: 'Evidence of a successful test', es: 'Evidencia de prueba exitosa' }, resp: 'Aurora + Mastertech' },
      { task: { pt: 'Testar internet com carga simulada', en: 'Test the internet with simulated load', es: 'Probar el internet con carga simulada' }, deliverable: { pt: 'Resultado de teste de velocidade e estabilidade', en: 'Speed and stability test results', es: 'Resultado de prueba de velocidad y estabilidad' }, resp: 'Aurora' },
      { task: { pt: 'Preparar plano B para falhas de conexão', en: 'Prepare a plan B for connection failures', es: 'Preparar un plan B para fallas de conexión' }, deliverable: { pt: 'Hotspots, rede alternativa ou conteúdo offline de apoio', en: 'Hotspots, alternative network or offline backup content', es: 'Hotspots, red alternativa o contenido offline de apoyo' }, resp: 'Aurora' },
      { task: { pt: 'Validar contas ou fluxo de acesso dos participantes', en: 'Validate participant accounts or access flow', es: 'Validar las cuentas o el flujo de acceso de los participantes' }, deliverable: { pt: 'Processo de login/cadastro testado', en: 'Login/registration process tested', es: 'Proceso de inicio de sesión/registro probado' }, resp: 'Aurora' },
      { task: { pt: 'Verificar restrições de rede em escolas ou espaços públicos', en: 'Check network restrictions at schools or public spaces', es: 'Verificar restricciones de red en escuelas o espacios públicos' }, deliverable: { pt: 'Liberação de domínios e permissões técnicas', en: 'Domain allowlisting and technical permissions', es: 'Liberación de dominios y permisos técnicos' }, resp: 'Aurora' },
      { task: { pt: 'Preparar equipamentos de projeção e áudio', en: 'Prepare projection and audio equipment', es: 'Preparar equipos de proyección y audio' }, deliverable: { pt: 'Checklist audiovisual', en: 'Audiovisual checklist', es: 'Checklist audiovisual' }, resp: 'Aurora' },
      { task: { pt: 'Criar kit técnico por evento', en: 'Assemble a technical kit per event', es: 'Crear un kit técnico por evento' }, deliverable: { pt: 'Cabos, extensões, adaptadores, réguas, carregadores', en: 'Cables, extensions, adapters, power strips, chargers', es: 'Cables, extensiones, adaptadores, regletas, cargadores' }, resp: 'Aurora' },
    ],
  },
  {
    n: 8,
    title: { pt: 'Jornada do evento presencial', en: 'In-person event journey', es: 'Jornada del evento presencial' },
    tasks: [
      { task: { pt: 'Adaptar blueprint da jornada desenhada pela Mastertech para cada local', en: 'Adapt the journey blueprint designed by Mastertech for each venue', es: 'Adaptar el blueprint de la jornada diseñada por Mastertech para cada sede' }, deliverable: { pt: 'Agenda local por evento', en: 'Local agenda per event', es: 'Agenda local por evento' }, resp: 'Aurora + Mastertech' },
      { task: { pt: 'Definir horário de chegada da equipe', en: 'Define the team arrival time', es: 'Definir el horario de llegada del equipo' }, deliverable: { pt: 'Call time operacional', en: 'Operational call time', es: 'Call time operativo' }, resp: 'Aurora' },
      { task: { pt: 'Definir fluxo de recepção e check-in', en: 'Define the reception and check-in flow', es: 'Definir el flujo de recepción y check-in' }, deliverable: { pt: 'Processo de credenciamento', en: 'Accreditation process', es: 'Proceso de acreditación' }, resp: 'Aurora' },
      { task: { pt: 'Preparar abertura institucional', en: 'Prepare the institutional opening', es: 'Preparar la apertura institucional' }, deliverable: { pt: 'Roteiro de boas-vindas', en: 'Welcome script', es: 'Guion de bienvenida' }, resp: 'Aurora' },
      { task: { pt: 'Organizar dinâmica para estudantes', en: 'Organize the activity for students', es: 'Organizar la dinámica para estudiantes' }, deliverable: { pt: 'Roteiro de oficina alinhado à metodologia', en: 'Workshop script aligned with the methodology', es: 'Guion de taller alineado con la metodología' }, resp: 'Aurora + Mastertech' },
      { task: { pt: 'Organizar sessão de engajamento familiar', en: 'Organize the family engagement session', es: 'Organizar la sesión de involucramiento familiar' }, deliverable: { pt: 'Roteiro para pais/responsáveis', en: 'Script for parents/guardians', es: 'Guion para padres/tutores' }, resp: 'Aurora' },
      { task: { pt: 'Definir momentos de coleta de dados durante o evento', en: 'Define data-collection moments during the event', es: 'Definir los momentos de recolección de datos durante el evento' }, deliverable: { pt: 'Checkpoints de registro', en: 'Recording checkpoints', es: 'Checkpoints de registro' }, resp: 'Aurora' },
      { task: { pt: 'Definir encerramento e próximos passos', en: 'Define the closing and next steps', es: 'Definir el cierre y los próximos pasos' }, deliverable: { pt: 'Roteiro de fechamento e convite para continuidade/Game Jam', en: 'Closing script and invitation to continuity/Game Jam', es: 'Guion de cierre e invitación a la continuidad/Game Jam' }, resp: 'Aurora' },
      { task: { pt: 'Criar plano de contingência para atrasos, baixa presença ou falhas técnicas', en: 'Create a contingency plan for delays, low attendance or technical failures', es: 'Crear un plan de contingencia para retrasos, baja asistencia o fallas técnicas' }, deliverable: { pt: 'Matriz de riscos por evento', en: 'Risk matrix per event', es: 'Matriz de riesgos por evento' }, resp: 'Aurora' },
    ],
  },
  {
    n: 9,
    title: { pt: 'Dados, métricas e comprovação de impacto', en: 'Data, metrics and impact evidence', es: 'Datos, métricas y comprobación de impacto' },
    tasks: [
      { task: { pt: 'Validar com Mastertech quais dados devem ser coletados', en: 'Validate with Mastertech which data must be collected', es: 'Validar con Mastertech qué datos deben recolectarse' }, deliverable: { pt: 'Dicionário de dados aprovado', en: 'Approved data dictionary', es: 'Diccionario de datos aprobado' }, resp: 'Aurora + Mastertech' },
      { task: { pt: 'Preparar formulário de inscrição com dados demográficos necessários', en: 'Prepare a registration form with the required demographic data', es: 'Preparar el formulario de inscripción con los datos demográficos necesarios' }, deliverable: { pt: 'Formulário validado', en: 'Validated form', es: 'Formulario validado' }, resp: 'Aurora' },
      { task: { pt: 'Preparar controle de presença', en: 'Prepare attendance tracking', es: 'Preparar el control de asistencia' }, deliverable: { pt: 'Lista de check-in por evento', en: 'Check-in list per event', es: 'Lista de check-in por evento' }, resp: 'Aurora' },
      { task: { pt: 'Criar mecanismo para verificar "net new creators"', en: 'Create a mechanism to verify "net new creators"', es: 'Crear un mecanismo para verificar "net new creators"' }, deliverable: { pt: 'Fluxo de comprovação de publicação no Roblox Studio', en: 'Flow to verify publishing in Roblox Studio', es: 'Flujo de comprobación de publicación en Roblox Studio' }, resp: 'Aurora + Mastertech' },
      { task: { pt: 'Coletar dados de estudantes, educadores, pais e responsáveis', en: 'Collect data from students, educators, parents and guardians', es: 'Recolectar datos de estudiantes, educadores, padres y tutores' }, deliverable: { pt: 'Base bruta padronizada', en: 'Standardized raw dataset', es: 'Base bruta estandarizada' }, resp: 'Aurora' },
      { task: { pt: 'Aplicar pesquisa de NPS/satisfação', en: 'Run an NPS/satisfaction survey', es: 'Aplicar una encuesta de NPS/satisfacción' }, deliverable: { pt: 'Formulário de avaliação', en: 'Evaluation form', es: 'Formulario de evaluación' }, resp: 'Aurora' },
      { task: { pt: 'Garantir fluxo contínuo de informações para Mastertech', en: 'Ensure a continuous flow of information to Mastertech', es: 'Garantizar un flujo continuo de información hacia Mastertech' }, deliverable: { pt: 'Envio periódico de base e indicadores', en: 'Periodic delivery of dataset and indicators', es: 'Envío periódico de base e indicadores' }, resp: 'Aurora' },
      { task: { pt: 'Preparar documentação de campo de cada evento', en: 'Prepare field documentation for each event', es: 'Preparar la documentación de campo de cada evento' }, deliverable: { pt: 'Fotos autorizadas, lista de presença, ocorrências e aprendizados', en: 'Authorized photos, attendance list, incidents and learnings', es: 'Fotos autorizadas, lista de asistencia, incidencias y aprendizajes' }, resp: 'Aurora' },
      { task: { pt: 'Consolidar dados das 5 ativações locais', en: 'Consolidate data from the 5 local activations', es: 'Consolidar los datos de las 5 activaciones locales' }, deliverable: { pt: 'Base única para relatório global', en: 'Single dataset for the global report', es: 'Base única para el reporte global' }, resp: 'Aurora + Mastertech' },
    ],
  },
  {
    n: 10,
    title: { pt: 'Privacidade, consentimento e proteção de menores', en: 'Privacy, consent and child protection', es: 'Privacidad, consentimiento y protección de menores' },
    tasks: [
      { task: { pt: 'Validar requisitos locais para participação de menores de idade', en: 'Validate local requirements for the participation of minors', es: 'Validar los requisitos locales para la participación de menores de edad' }, deliverable: { pt: 'Checklist jurídico-operacional', en: 'Legal-operational checklist', es: 'Checklist jurídico-operativo' }, resp: 'Aurora' },
      { task: { pt: 'Criar ou adaptar termo de autorização de pais/responsáveis', en: 'Create or adapt the parent/guardian authorization form', es: 'Crear o adaptar el formulario de autorización de padres/tutores' }, deliverable: { pt: 'Termo em espanhol mexicano', en: 'Form in Mexican Spanish', es: 'Formulario en español mexicano' }, resp: 'Aurora + Roblox/Mastertech' },
      { task: { pt: 'Definir política de uso de imagem', en: 'Define the image-use policy', es: 'Definir la política de uso de imagen' }, deliverable: { pt: 'Termo de imagem e consentimento', en: 'Image and consent release', es: 'Consentimiento y autorización de imagen' }, resp: 'Aurora' },
      { task: { pt: 'Garantir armazenamento seguro dos dados coletados', en: 'Ensure secure storage of the collected data', es: 'Garantizar el almacenamiento seguro de los datos recolectados' }, deliverable: { pt: 'Procedimento de proteção de dados', en: 'Data protection procedure', es: 'Procedimiento de protección de datos' }, resp: 'Aurora' },
      { task: { pt: 'Separar dados operacionais de dados sensíveis', en: 'Separate operational data from sensitive data', es: 'Separar los datos operativos de los datos sensibles' }, deliverable: { pt: 'Estrutura de base segura', en: 'Secure dataset structure', es: 'Estructura de base segura' }, resp: 'Aurora' },
      { task: { pt: 'Orientar equipe local sobre tratamento de dados de menores', en: "Brief the local team on handling minors' data", es: 'Orientar al equipo local sobre el tratamiento de datos de menores' }, deliverable: { pt: 'Briefing de privacidade', en: 'Privacy briefing', es: 'Briefing de privacidad' }, resp: 'Aurora' },
      { task: { pt: 'Confirmar alinhamento com DPA Roblox/Mastertech quando aplicável', en: 'Confirm alignment with the Roblox/Mastertech DPA when applicable', es: 'Confirmar la alineación con el DPA Roblox/Mastertech cuando aplique' }, deliverable: { pt: 'Registro de conformidade', en: 'Compliance record', es: 'Registro de conformidad' }, resp: 'Aurora + Mastertech/Roblox' },
    ],
  },
  {
    n: 11,
    title: { pt: 'Game Jams e continuidade pós-evento', en: 'Game Jams and post-event continuity', es: 'Game Jams y continuidad post-evento' },
    tasks: [
      { task: { pt: 'Entender regras, elegibilidade e rubricas definidas pela Mastertech', en: 'Understand the rules, eligibility and rubrics defined by Mastertech', es: 'Entender las reglas, elegibilidad y rúbricas definidas por Mastertech' }, deliverable: { pt: 'Guia local de Game Jam', en: 'Local Game Jam guide', es: 'Guía local de Game Jam' }, resp: 'Aurora + Mastertech' },
      { task: { pt: 'Preparar comunicação para convidar participantes aos desafios', en: 'Prepare communication to invite participants to the challenges', es: 'Preparar la comunicación para invitar a los participantes a los desafíos' }, deliverable: { pt: 'Convite pós-evento', en: 'Post-event invitation', es: 'Invitación post-evento' }, resp: 'Aurora' },
      { task: { pt: 'Definir canal de suporte aos jovens participantes', en: 'Define a support channel for young participants', es: 'Definir un canal de soporte para los jóvenes participantes' }, deliverable: { pt: 'WhatsApp, Discord, e-mail ou outro canal aprovado', en: 'WhatsApp, Discord, email or another approved channel', es: 'WhatsApp, Discord, correo u otro canal aprobado' }, resp: 'Aurora' },
      { task: { pt: 'Organizar acompanhamento dos projetos iniciados nos eventos', en: 'Organize follow-up of the projects started at the events', es: 'Organizar el seguimiento de los proyectos iniciados en los eventos' }, deliverable: { pt: 'Lista de participantes e status dos projetos', en: 'List of participants and project status', es: 'Lista de participantes y estado de los proyectos' }, resp: 'Aurora' },
      { task: { pt: 'Apoiar submissão de experiências criadas pelos estudantes', en: 'Support submission of experiences created by students', es: 'Apoyar el envío de experiencias creadas por los estudiantes' }, deliverable: { pt: 'Registro de submissões', en: 'Record of submissions', es: 'Registro de envíos' }, resp: 'Aurora' },
      { task: { pt: 'Garantir que os projetos submetidos possam ser avaliados conforme rubrica', en: 'Ensure submitted projects can be evaluated per the rubric', es: 'Garantizar que los proyectos enviados puedan evaluarse según la rúbrica' }, deliverable: { pt: 'Pacote de avaliação por participante/equipe', en: 'Evaluation package per participant/team', es: 'Paquete de evaluación por participante/equipo' }, resp: 'Aurora' },
      { task: { pt: 'Enviar resultados e evidências à Mastertech', en: 'Send results and evidence to Mastertech', es: 'Enviar resultados y evidencias a Mastertech' }, deliverable: { pt: 'Relatório de continuidade', en: 'Continuity report', es: 'Reporte de continuidad' }, resp: 'Aurora' },
    ],
  },
];

export const CHECKLIST_TOTAL = CHECKLIST.reduce((s, sec) => s + sec.tasks.length, 0);
